'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { products, money } from '@/lib/products';
import { supabaseBrowser } from '@/lib/supabase';
type CartItem = { id: string; quantity: number; size: string };
export default function Checkout() {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [catalog, setCatalog] = useState(products);
  const [email, setEmail] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { setCart(JSON.parse(localStorage.getItem('tade-cart') || '[]')); if (process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) { const db = supabaseBrowser(); db.from('products').select('id,name,category,price_kobo,image,color,tag').eq('active',true).then(({data}) => { if(data?.length) setCatalog(data.map(p => ({...p,price:Math.round(p.price_kobo/100)}))); }); } }, []);
  const rows = useMemo(() => cart.map(i => ({ ...i, product: catalog.find(p => p.id === i.id) })).filter(i => i.product), [cart,catalog]);
  const total = rows.reduce((sum, row) => sum + row.product!.price * row.quantity, 0);
  function update(id: string, change: number) { const next = cart.map(x => x.id === id ? { ...x, quantity: x.quantity + change } : x).filter(x => x.quantity > 0); setCart(next); localStorage.setItem('tade-cart', JSON.stringify(next)); window.dispatchEvent(new Event('tade-cart-change')); }
  async function pay(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const response = await fetch('/api/checkout', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, items: rows.map(i => ({ id: i.id, quantity: i.quantity, size: i.size })) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not start checkout.'); window.location.assign(data.url); } catch (err) { setError(err instanceof Error ? err.message : 'Something went wrong.'); setBusy(false); } }
  return <section className="checkout-wrap"><Link href="/" className="back-link">← &nbsp;Back to the shop</Link><div className="checkout-title"><span className="eyebrow">A VERY GOOD CHOICE</span><h1>Your bag.</h1></div>{rows.length === 0 ? <div className="empty-bag"><span>✳</span><h2>Your next pair is waiting.</h2><p>Your bag is empty for now.</p><Link className="button button-dark" href="/#shop">Explore the collection ↗</Link></div> : <div className="checkout-layout"><div className="bag-items">{rows.map(({ id, product, quantity, size }) => <article className="bag-row" key={id}><div className="bag-photo" style={{ backgroundImage: `url(https://images.unsplash.com/${product!.image}?auto=format&fit=crop&w=400&q=80)` }}/><div className="bag-detail"><span className="product-type">{product!.category}</span><h2>{product!.name}</h2><label>Size <select value={size} onChange={e => { const next = cart.map(x => x.id === id ? {...x,size:e.target.value} : x); setCart(next); localStorage.setItem('tade-cart', JSON.stringify(next)); }}><option>36</option><option>37</option><option>38</option><option>39</option><option>40</option><option>41</option><option>42</option><option>43</option></select></label><div className="quantity"><button onClick={() => update(id,-1)} aria-label="Decrease quantity">−</button><span>{quantity}</span><button onClick={() => update(id,1)} aria-label="Increase quantity">＋</button></div></div><strong>{money(product!.price * quantity)}</strong></article>)}</div><form className="order-panel" onSubmit={pay}><span className="eyebrow">CHECKOUT</span><h2>Nearly yours.</h2><label className="field-label">Email for your order updates<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com"/></label><div className="subtotal"><span>Subtotal</span><strong>{money(total)}</strong></div><div className="subtotal muted"><span>Delivery</span><span>Calculated at checkout</span></div><p className="secure-note">Secure payment · Shipping details collected by Stripe</p>{error && <p className="form-error">{error}</p>}<button className="button button-dark pay-button" disabled={busy}>{busy ? 'Opening secure checkout…' : <>Continue to payment <span>→</span></>}</button><small>By continuing, you agree to our store policies. You’ll receive an email once your order is confirmed.</small></form></div>}</section>;
}
